// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shellmate.Persistence;

#nullable disable

namespace Shellmate.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Shellmate.Models.AssistantConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssistantConversations");
                });

            modelBuilder.Entity("Shellmate.Models.AssistantMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("AssistantMessages");
                });

            modelBuilder.Entity("Shellmate.Models.ConnectionNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerminalConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TerminalConnectionId", "NormalizedTitle")
                        .IsUnique();

                    b.ToTable("ConnectionNotes");
                });

            modelBuilder.Entity("Shellmate.Models.LlmProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestAuthType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastChatTestCredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestEndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestModelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastChatTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChatTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialSourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders");
                });

            modelBuilder.Entity("Shellmate.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenSecretName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshTokenSecretName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("Shellmate.Models.StoredSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StoredSecrets");
                });

            modelBuilder.Entity("Shellmate.Models.TerminalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalShellArguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalShellPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalWorkingDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivateKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshAuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShellKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrustedHostKeyBits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrustedHostKeyFingerprintSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrustedHostKeyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TerminalConnections");
                });

            modelBuilder.Entity("Shellmate.Models.AssistantMessage", b =>
                {
                    b.HasOne("Shellmate.Models.AssistantConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Shellmate.Models.ConnectionNote", b =>
                {
                    b.HasOne("Shellmate.Models.TerminalConnection", "TerminalConnection")
                        .WithMany("Notes")
                        .HasForeignKey("TerminalConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerminalConnection");
                });

            modelBuilder.Entity("Shellmate.Models.LlmProvider", b =>
                {
                    b.HasOne("Shellmate.Models.LlmProvider", "CredentialSource")
                        .WithMany("ChildModels")
                        .HasForeignKey("CredentialSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CredentialSource");
                });

            modelBuilder.Entity("Shellmate.Models.OAuthToken", b =>
                {
                    b.HasOne("Shellmate.Models.LlmProvider", "Provider")
                        .WithMany("OAuthTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Shellmate.Models.AssistantConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Shellmate.Models.LlmProvider", b =>
                {
                    b.Navigation("ChildModels");

                    b.Navigation("OAuthTokens");
                });

            modelBuilder.Entity("Shellmate.Models.TerminalConnection", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
