import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import type { AccessMode, ChatContext, ChatProviderEntry, ConnectionInput, ConnectionSummary, Conversation, Note, Snapshot, TerminalSnapshot } from '../shared/types';

const api = () => window.shellmate;
const errorText = (error: unknown) => error instanceof Error ? error.message : 'Operation failed.';
const emptyConnection = (): ConnectionInput => ({ name: '', kind: 'ssh', host: '', port: 22, username: '', auth: 'password', privateKeyPath: '', shell: 'auto', localShellPath: '', localShellArgs: '', localCwd: '' });
const connectionInput = (value: ConnectionSummary): ConnectionInput => ({ id: value.id, name: value.name, kind: value.kind, host: value.host, port: value.port, username: value.username, auth: value.auth, privateKeyPath: value.privateKeyPath, shell: value.shell, localShellPath: value.localShellPath, localShellArgs: value.localShellArgs, localCwd: value.localCwd });

function TerminalPane({ profile, session, onConnect, onDisconnect, onTakeOver }: { profile: ConnectionSummary; session?: TerminalSnapshot; onConnect: () => void; onDisconnect: () => void; onTakeOver: () => void }) {
  const host = useRef<HTMLDivElement>(null);
  const terminal = useRef<Terminal | null>(null);
  const owner = useRef(session?.owner);
  owner.current = session?.owner;
  useEffect(() => {
    if (!session || !host.current) return;
    const term = new Terminal({ convertEol: false, cursorBlink: true, fontFamily: 'Cascadia Code, Consolas, monospace', fontSize: 12, lineHeight: 1.35, theme: { background: '#151a19', foreground: '#dbe8df', cursor: '#9acbae', selectionBackground: '#315440' }, scrollback: 3000 });
    const fit = new FitAddon(); term.loadAddon(fit); term.open(host.current); terminal.current = term;
    term.write(session.output); fit.fit();
    let lastSeq = session.seq;
    const stopEvents = api().onTerminal(event => { if (event.id === session.id && event.seq > lastSeq) { lastSeq = event.seq; term.write(event.data); } });
    const input = term.onData(data => { if (!owner.current) void api().write(profile.id, data).catch(() => undefined); });
    const resize = new ResizeObserver(() => { if (!host.current) return; fit.fit(); void api().resize(profile.id, term.cols, term.rows).catch(() => undefined); });
    resize.observe(host.current);
    return () => { resize.disconnect(); input.dispose(); stopEvents(); term.dispose(); terminal.current = null; };
  }, [session?.id, profile.id]);
  return <div className="terminal-pane">
    <div className="terminal-heading"><span className={`status-dot ${session ? 'on' : ''}`} /> <strong>{profile.name}</strong><span className="subtle">{profile.kind === 'ssh' ? `${profile.username}@${profile.host}:${profile.port}` : 'Local shell'}</span><span className="fill" />
      {session ? <button onClick={onDisconnect} disabled={Boolean(session.owner && session.owner.phase !== 'returning-control')}>Disconnect</button> : <button className="primary" onClick={onConnect}>Connect</button>}
    </div>
    {session ? <><div ref={host} className="terminal-canvas" aria-label={`${profile.name} terminal`} /><div className={`terminal-ownership ${session.owner ? 'owned' : ''}`}>
      {session.owner ? <><span className="agent-mark">✦</span> <span>Agent controlling · {session.owner.phase === 'command-running' ? 'Command running' : session.owner.phase === 'returning-control' ? 'Returning control…' : 'Working'}</span><span className="fill" /><button onClick={onTakeOver}>Take over</button></>
        : <><span className="status-dot on" /> You have control<span className="fill" /><span className="subtle">{session.shell}</span></>}
    </div></> : <div className="terminal-empty"><div className="terminal-empty-icon">⌘</div><strong>Terminal disconnected</strong><span>Connect to work in this shell. Agent access follows the conversation targets.</span><button className="primary" onClick={onConnect}>Connect {profile.name}</button></div>}
  </div>;
}

function ConnectionDialog({ profile, onClose, onSave, onDelete }: { profile?: ConnectionSummary; onClose: () => void; onSave: (input: ConnectionInput) => Promise<void>; onDelete?: () => Promise<void> }) {
  const [draft, setDraft] = useState<ConnectionInput>(profile ? connectionInput(profile) : emptyConnection());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const update = <K extends keyof ConnectionInput>(key: K, value: ConnectionInput[K]) => setDraft(current => ({ ...current, [key]: value }));
  const save = async () => { setBusy(true); setError(''); try { await onSave(draft); onClose(); } catch (error) { setError(errorText(error)); } finally { setBusy(false); } };
  return <div className="modal-backdrop" role="presentation"><div className="dialog connection-dialog" role="dialog" aria-modal="true" aria-label={profile ? 'Edit connection' : 'Add connection'}>
    <div className="dialog-head"><h2>{profile ? 'Edit connection' : 'Add connection'}</h2><button onClick={onClose} aria-label="Close">×</button></div>
    <div className="dialog-body"><div className="form-grid">
      <label>Name<input value={draft.name} onChange={e => update('name', e.target.value)} placeholder="web-01" /></label>
      <label>Type<select value={draft.kind} onChange={e => update('kind', e.target.value as ConnectionInput['kind'])}><option value="ssh">SSH</option><option value="local">Local shell</option></select></label>
      {draft.kind === 'ssh' ? <>
        <label>Host<input value={draft.host} onChange={e => update('host', e.target.value)} placeholder="server.example.com" /></label>
        <label>Port<input type="number" value={draft.port} onChange={e => update('port', Number(e.target.value))} /></label>
        <label>Username<input value={draft.username} onChange={e => update('username', e.target.value)} /></label>
        <label>Authentication<select value={draft.auth} onChange={e => update('auth', e.target.value as ConnectionInput['auth'])}><option value="password">Password</option><option value="key">Private key</option></select></label>
        {draft.auth === 'key' && <label className="wide">Private key path<input value={draft.privateKeyPath} onChange={e => update('privateKeyPath', e.target.value)} placeholder="C:\Users\you\.ssh\id_ed25519" /></label>}
        <label className="wide">{draft.auth === 'password' ? 'SSH password' : 'Key passphrase'}<input type="password" value={draft.auth === 'password' ? draft.password ?? '' : draft.passphrase ?? ''} onChange={e => update(draft.auth === 'password' ? 'password' : 'passphrase', e.target.value)} placeholder={profile ? 'Leave blank to keep saved credential' : 'Enter credential'} /></label>
        {profile && <label className="check wide"><input type="checkbox" checked={(draft.auth === 'password' ? draft.passwordAction : draft.passphraseAction) === 'remove'} onChange={e => update(draft.auth === 'password' ? 'passwordAction' : 'passphraseAction', e.target.checked ? 'remove' : 'keep')} /> Remove saved {draft.auth === 'password' ? 'password' : 'passphrase'}</label>}
      </> : <>
        <label className="wide">Shell executable<input value={draft.localShellPath} onChange={e => update('localShellPath', e.target.value)} placeholder="Default shell" /></label>
        <label className="wide">Arguments<input value={draft.localShellArgs} onChange={e => update('localShellArgs', e.target.value)} /></label>
        <label className="wide">Working directory<input value={draft.localCwd} onChange={e => update('localCwd', e.target.value)} placeholder="App directory" /></label>
      </>}
      <label>Shell syntax<select value={draft.shell} onChange={e => update('shell', e.target.value as ConnectionInput['shell'])}><option value="auto">Detect</option><option value="posix">POSIX</option><option value="powershell">PowerShell</option><option value="cmd">cmd</option></select></label>
    </div>{error && <p className="error" role="alert">{error}</p>}</div>
    <div className="dialog-actions">{profile && onDelete && <button className="danger" onClick={() => { if (window.confirm(`Delete ${profile.name} and its notes from all workspaces?`)) void onDelete().then(onClose).catch(error => setError(errorText(error))); }}>Delete connection</button>}<span className="fill" /><button onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={() => void save()}>Save connection</button></div>
  </div></div>;
}

function ProvidersDialog({ snapshot, onClose, act }: { snapshot: Snapshot; onClose: () => void; act: (action: () => Promise<unknown>) => Promise<unknown> }) {
  const [label, setLabel] = useState(''); const [kind, setKind] = useState<ChatProviderEntry['kind']>('chat-completions'); const [url, setUrl] = useState(''); const [key, setKey] = useState(''); const [keyAction, setKeyAction] = useState<'keep' | 'remove'>('keep');
  const [editing, setEditing] = useState<string | undefined>(); const [providerId, setProviderId] = useState(''); const [slug, setSlug] = useState(''); const [efforts, setEfforts] = useState(''); const [test, setTest] = useState<string>(''); const [modelId, setModelId] = useState<string | undefined>();
  const edit = (entry: ChatProviderEntry) => { setEditing(entry.id); setLabel(entry.label); setKind(entry.kind); setUrl(entry.baseUrl); setKey(''); setKeyAction('keep'); };
  const saveProvider = async () => { const saved = await act(() => api().saveChatProvider({ id: editing, label, baseUrl: url, kind, apiKey: key || undefined, keyAction: key ? 'replace' : keyAction })); if (saved === null) return; setEditing(undefined); setLabel(''); setUrl(''); setKey(''); setKeyAction('keep'); };
  const testModel = async () => { const response = await act(() => api().testChatModel({ providerId, slug, efforts: efforts.split(',').map(x => x.trim()).filter(Boolean) })); setTest(response === null ? '' : JSON.stringify(response)); };
  const saveModel = async () => { const saved = await act(() => api().saveChatModel({ id: modelId, providerId, slug, efforts: efforts.split(',').map(x => x.trim()).filter(Boolean) })); if (saved === null) return; setModelId(undefined); setSlug(''); setEfforts(''); setTest(''); };
  return <div className="modal-backdrop" role="presentation"><div className="dialog providers-dialog" role="dialog" aria-modal="true" aria-label="Chat providers">
    <div className="dialog-head"><h2>Chat providers</h2><button onClick={onClose} aria-label="Close">×</button></div><div className="dialog-body">
      <section className="settings-section"><div className="section-heading"><h3>Codex account</h3><span className={snapshot.providers.codexReady ? 'good' : 'subtle'}>{snapshot.providers.codexReady ? 'Connected' : snapshot.providers.loginPending ? 'Waiting for login' : 'Disconnected'}</span></div>
        <p className="subtle">Use your OpenAI account for the built-in Codex models.</p><div className="row">{snapshot.providers.codexReady ? <button onClick={() => void act(() => api().logout())}>Sign out</button> : snapshot.providers.loginPending ? <button onClick={() => void act(() => api().cancelLogin())}>Cancel login</button> : <button className="primary" onClick={() => void act(() => api().startLogin())}>Sign in</button>}</div>
      </section>
      <section className="settings-section"><div className="section-heading"><h3>API providers</h3><span className="subtle">Chat Completions · Responses · Anthropic</span></div>
        {snapshot.providers.providers.map(entry => <div className="settings-row" key={entry.id}><span><strong>{entry.label}</strong><small>{entry.kind} · {entry.baseUrl}</small></span><span className="fill" /><button onClick={() => edit(entry)}>Edit</button><button className="danger" onClick={() => void act(() => api().deleteChatProvider(entry.id))}>Delete</button></div>)}
        <div className="form-grid"><label>Label<input value={label} onChange={e => setLabel(e.target.value)} placeholder="Local model" /></label><label>Transport<select value={kind} onChange={e => setKind(e.target.value as ChatProviderEntry['kind'])}><option value="chat-completions">Chat Completions</option><option value="responses">Responses</option><option value="anthropic">Anthropic</option></select></label><label className="wide">Base URL<input value={url} onChange={e => setUrl(e.target.value)} placeholder="http://localhost:1234/v1" /></label><label className="wide">API key<input type="password" value={key} onChange={e => setKey(e.target.value)} placeholder={editing ? 'Leave blank to keep saved key' : 'Optional for local servers'} /></label></div>
        {editing && <label className="check"><input type="checkbox" checked={keyAction === 'remove'} onChange={e => setKeyAction(e.target.checked ? 'remove' : 'keep')} /> Remove saved key</label>}
        <button onClick={() => void saveProvider()}>{editing ? 'Update provider' : 'Add provider'}</button>
      </section>
      <section className="settings-section"><h3>Models</h3>{snapshot.providers.chatModels.filter(model => !model.builtIn).map(model => <div className="settings-row" key={model.id}><span><strong>{model.label}</strong><small>Efforts: {model.efforts.join(', ') || 'default'}</small></span><span className="fill" /><button onClick={() => { setModelId(model.id); setProviderId(snapshot.providers.providers.find(p => p.label === model.providerLabel)?.id ?? ''); setSlug(model.slug); setEfforts(model.efforts.join(', ')); setTest(''); }}>Edit</button><button className="danger" onClick={() => void act(() => api().deleteChatModel(model.id))}>Delete</button></div>)}
        <div className="form-grid"><label>Provider<select value={providerId} onChange={e => setProviderId(e.target.value)}><option value="">Choose provider</option>{snapshot.providers.providers.map(provider => <option key={provider.id} value={provider.id}>{provider.label}</option>)}</select></label><label>Model ID<input value={slug} onChange={e => setSlug(e.target.value)} placeholder="model-name" /></label><label className="wide">Reasoning efforts, comma separated<input value={efforts} onChange={e => setEfforts(e.target.value)} placeholder="Leave blank for provider default" /></label></div>
        <div className="row"><button disabled={!providerId || !slug} onClick={() => void testModel()}>Test model and efforts</button><button className="primary" disabled={!test} onClick={() => void saveModel()}>Save tested model</button></div>{test && <pre className="test-result">{test}</pre>}
      </section>{snapshot.providers.error && <p className="error">{snapshot.providers.error}</p>}
    </div><div className="dialog-actions"><span className="fill" /><button onClick={onClose}>Done</button></div>
  </div></div>;
}

function NotesDrawer({ connection, act, onClose }: { connection: ConnectionSummary; act: (action: () => Promise<unknown>) => Promise<unknown>; onClose: () => void }) {
  const [notes, setNotes] = useState<Note[]>([]); const [active, setActive] = useState<string | null>(null); const [title, setTitle] = useState(''); const [content, setContent] = useState('');
  useEffect(() => { let live = true; void api().listNotes(connection.id).then(values => { if (live) setNotes(values); }); return () => { live = false; }; }, [connection.id]);
  const select = (note: Note) => { setActive(note.id); setTitle(note.title); setContent(note.content); };
  const reload = async () => setNotes(await api().listNotes(connection.id));
  const save = async () => { const note = await act(() => api().saveNote(connection.id, { id: active ?? undefined, title, content })) as Note; if (note) { setActive(note.id); await reload(); } };
  return <aside className="notes-drawer"><div className="drawer-head"><div><strong>Connection notes</strong><small>{connection.name}</small></div><button onClick={onClose} aria-label="Close notes">×</button></div><div className="note-list"><button className="new-note" onClick={() => { setActive(null); setTitle(''); setContent(''); }}>+ New note</button>{notes.map(note => <button key={note.id} className={active === note.id ? 'selected' : ''} onClick={() => select(note)}>{note.title}</button>)}</div><div className="note-editor"><input aria-label="Note title" value={title} onChange={e => setTitle(e.target.value)} placeholder="Note title" /><textarea aria-label="Note content" value={content} onChange={e => setContent(e.target.value)} placeholder="Machine purpose, configuration, discoveries…" /><div className="row"><button className="primary" disabled={!title.trim()} onClick={() => void save()}>Save note</button>{active && <button className="danger" onClick={() => void act(() => api().deleteNote(connection.id, active)).then(() => { setActive(null); setTitle(''); setContent(''); void reload(); })}>Delete</button>}</div></div></aside>;
}

export default function App() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [selectedConversation, setSelectedConversation] = useState<string | null>(null); const [selectedConnection, setSelectedConnection] = useState<string | null>(null); const [secondConnection, setSecondConnection] = useState<string | null>(null);
  const [showSplit, setShowSplit] = useState(false); const [showNotes, setShowNotes] = useState(false); const [showHistory, setShowHistory] = useState(false); const [showTargets, setShowTargets] = useState(false); const [showCatalog, setShowCatalog] = useState(false); const [showProviders, setShowProviders] = useState(false);
  const [editConnection, setEditConnection] = useState<ConnectionSummary | 'new' | null>(null); const [draft, setDraft] = useState(''); const [message, setMessage] = useState(''); const [context, setContext] = useState<ChatContext | null>(null); const [chatWidth, setChatWidth] = useState(35);
  const transcript = useRef<HTMLDivElement>(null); const follow = useRef(true); const refreshSeq = useRef(0);
  const refresh = useCallback(async () => { const index = ++refreshSeq.current; const value = await api().snapshot(); if (index === refreshSeq.current) setSnapshot(value); }, []);
  useEffect(() => { void refresh().catch(error => setMessage(errorText(error))); return api().onChanged(() => { void refresh().catch(() => undefined); }); }, [refresh]);
  const act = useCallback(async (action: () => Promise<unknown>) => { try { const result = await action(); await refresh(); setMessage(''); return result; } catch (error) { setMessage(errorText(error)); return null; } }, [refresh]);
  const workspaceConnections = useMemo(() => snapshot?.connections.filter(item => snapshot.workspaceConnectionIds.includes(item.id)) ?? [], [snapshot]);
  const conversation = snapshot?.conversations.find(c => c.id === selectedConversation) ?? snapshot?.conversations[0];
  const activeConnection = workspaceConnections.find(item => item.id === selectedConnection) ?? workspaceConnections[0];
  const splitConnection = workspaceConnections.find(item => item.id === secondConnection && item.id !== activeConnection?.id) ?? workspaceConnections.find(item => item.id !== activeConnection?.id);
  const messages = snapshot?.messages.filter(item => item.conversationId === conversation?.id) ?? [];
  const targets = snapshot?.targets.filter(item => item.conversationId === conversation?.id) ?? [];
  const approval = snapshot?.approvals.find(item => item.conversationId === conversation?.id);
  useEffect(() => { if (follow.current && transcript.current) transcript.current.scrollTop = transcript.current.scrollHeight; }, [messages.length, messages.at(-1)?.text, approval?.id, conversation?.id]);
  useEffect(() => { if (!conversation) return; let live = true; const timer = setTimeout(() => { void api().chatContext(conversation.id, draft).then(value => { if (live) setContext(value); }).catch(() => { if (live) setContext(null); }); }, 300); return () => { live = false; clearTimeout(timer); }; }, [conversation?.id, draft, messages.length, messages.at(-1)?.text, snapshot?.providers.activeChat.modelId]);
  const selectedModel = snapshot?.providers.chatModels.find(item => item.id === snapshot.providers.activeChat.modelId);
  const submit = () => { if (!conversation || !draft.trim()) return; const text = draft.trim(); setDraft(''); follow.current = true; void act(() => api().sendMessage(conversation.id, text)); };
  const connect = (id: string) => void act(() => api().connect(id));
  const disconnect = (id: string) => void act(() => api().disconnect(id));
  const takeOver = (id: string) => void act(() => api().takeOver(id));
  const setTarget = (id: string, access: AccessMode | null) => { if (conversation) void act(() => api().setTarget(conversation.id, id, access)); };
  const editWorkspace = () => { const name = window.prompt('Workspace name', snapshot?.workspaces.find(item => item.id === snapshot.activeWorkspaceId)?.name ?? ''); if (name?.trim() && snapshot) void act(() => api().renameWorkspace(snapshot.activeWorkspaceId, name)); };
  const createWorkspace = () => { const name = window.prompt('New workspace name'); if (name?.trim()) void act(() => api().createWorkspace(name)).then(() => { setSelectedConversation(null); setSelectedConnection(null); }); };
  const renameConversation = () => { if (!conversation) return; const title = window.prompt('Conversation title', conversation.title); if (title?.trim()) void act(() => api().renameConversation(conversation.id, title)); };
  const saveConnection = async (input: ConnectionInput) => { const result = await api().saveConnection(input); await refresh(); if (!result) throw new Error('Connection could not be saved.'); };
  if (!snapshot) return <div className="loading">Loading Shellmate…</div>;
  return <div className="app-shell">
    <header className="app-header"><div className="brand"><span className="brand-mark">⌘</span><strong>shellmate</strong></div><div className="header-divider" /><select aria-label="Workspace" value={snapshot.activeWorkspaceId} onChange={e => void act(() => api().setActiveWorkspace(e.target.value)).then(() => { setSelectedConversation(null); setSelectedConnection(null); })}>{snapshot.workspaces.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button title="Rename workspace" onClick={editWorkspace}>Rename</button><button title="New workspace" onClick={createWorkspace}>+ Workspace</button><span className="subtle">{workspaceConnections.length} connections</span><span className="fill" />
      <button onClick={() => setShowProviders(true)}>Providers</button>
    </header>
    <div className="work-area" style={{ '--chat-width': `${chatWidth}%` } as React.CSSProperties}>
      <section className="chat-pane">
        <div className="chat-model-bar">
          <select className="model-select" aria-label="Chat model" value={snapshot.providers.activeChat.modelId} onChange={e => void act(() => api().setActiveChat({ modelId: e.target.value, effort: snapshot.providers.chatModels.find(item => item.id === e.target.value)?.efforts[0] ?? '' }))}>{snapshot.providers.chatModels.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select>
          {selectedModel?.efforts.length ? <select className="effort-select" aria-label="Reasoning effort" value={snapshot.providers.activeChat.effort} onChange={e => void act(() => api().setActiveChat({ modelId: selectedModel.id, effort: e.target.value }))}>{selectedModel.efforts.map(item => <option key={item} value={item}>{item}</option>)}</select> : null}
        </div>
        <div className="chat-heading"><div className="overline">Conversation</div><div className="row"><button className="conversation-title" onClick={renameConversation}>{conversation?.title ?? 'New conversation'} <span className="subtle">✎</span></button><span className="fill" /><button title="Conversation history" onClick={() => setShowHistory(!showHistory)}>History</button><button title="New conversation" onClick={() => void act(() => api().createConversation()).then(value => { if (typeof value === 'string') setSelectedConversation(value); })}>＋</button></div></div>
        {showHistory && <div className="history-list">{snapshot.conversations.map(item => <button key={item.id} className={item.id === conversation?.id ? 'selected' : ''} onClick={() => { setSelectedConversation(item.id); setShowHistory(false); follow.current = true; }}>{item.title}{snapshot.approvals.some(approval => approval.conversationId === item.id) && <span className="needs-attention">!</span>}</button>)}</div>}
        <div className="target-bar"><span className="subtle">Targets</span>{targets.map(target => { const profile = snapshot.connections.find(item => item.id === target.connectionId); return <span className={`target-chip ${target.access}`} key={target.connectionId}>{profile?.name ?? 'Missing'} · {target.access}</span>; })}<button title="Choose targets" onClick={() => setShowTargets(!showTargets)}>＋</button></div>
        {showTargets && <div className="target-picker"><div className="overline">Conversation access</div>{workspaceConnections.map(profile => { const selected = targets.find(target => target.connectionId === profile.id); return <div className="settings-row" key={profile.id}><strong>{profile.name}</strong><span className="fill" /><select aria-label={`${profile.name} assistant access`} value={selected?.access ?? 'none'} onChange={e => setTarget(profile.id, e.target.value === 'none' ? null : e.target.value as AccessMode)}><option value="none">No target</option><option value="disabled">Disabled</option><option value="ask">Ask before commands</option><option value="autonomous">Autonomous</option></select></div>; })}</div>}
        <div className="transcript" ref={transcript} onScroll={e => { const target = e.currentTarget; follow.current = target.scrollHeight - target.scrollTop - target.clientHeight < 50; }}>
          {!messages.length && <div className="chat-empty"><span className="sparkle">✦</span><h2>Ask about your machines</h2><p>Pick one or more targets, then ask Shellmate to inspect, compare, or help operate them.</p></div>}
          {messages.map(item => <div key={item.id} className={`message ${item.role}`}><div className="message-label">{item.role === 'assistant' ? '✦ Shellmate' : item.role === 'tool' ? `${snapshot.connections.find(c => c.id === item.targetId)?.name ?? 'Tool'} · ${item.toolName ?? 'activity'}` : 'You'}<span className="fill" /><time>{new Date(item.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div><div className="message-text">{item.text || (item.status === 'running' ? 'Thinking…' : '')}</div>{item.status === 'failed' && <small className="error">Failed</small>}</div>)}
          {approval && <div className="approval-card"><div className="approval-title">◆ Approval required · {snapshot.connections.find(c => c.id === approval.connectionId)?.name}</div><p>The assistant requests permission to run this command:</p><pre>{approval.command}</pre><div className="row"><button className="primary" onClick={() => void act(() => api().resolveApproval(approval.id, true))}>Approve once</button><button onClick={() => void act(() => api().resolveApproval(approval.id, false))}>Reject</button></div></div>}
        </div>
        <div className="composer-shell"><div className="composer"><textarea value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); } }} placeholder="Ask about your machines…" aria-label="Message Shellmate" /><div className="row"><span className="subtle">{targets.filter(item => item.access !== 'disabled').length} targets</span><span className="fill" />{conversation && snapshot.activeTurns.includes(conversation.id) ? <button onClick={() => void act(() => api().cancelTurn(conversation.id))}>Stop response</button> : <button className="primary" onClick={submit} disabled={!draft.trim()}>Send ↑</button>}</div></div><div className="composer-meta"><span>Enter to send · Shift+Enter for newline</span><span>{context ? `Context ~${Math.round(context.tokens / 1000)}k${context.limit ? ` / ${Math.round(context.limit / 1000)}k` : ''}` : 'Context unavailable'}</span></div></div>
      </section>
      <div className="resize-handle" role="separator" aria-label="Resize chat" onPointerDown={event => { const start = event.clientX; const original = chatWidth; const total = event.currentTarget.parentElement?.clientWidth ?? 1200; event.currentTarget.setPointerCapture(event.pointerId); const move = (e: PointerEvent) => setChatWidth(Math.max(28, Math.min(48, original + (e.clientX - start) / total * 100))); const stop = () => { event.currentTarget.removeEventListener('pointermove', move); event.currentTarget.removeEventListener('pointerup', stop); }; event.currentTarget.addEventListener('pointermove', move); event.currentTarget.addEventListener('pointerup', stop); }} />
      <section className="terminal-area"><div className="terminal-tabs">{workspaceConnections.map(item => { const connected = snapshot.terminals.find(session => session.connectionId === item.id); return <button key={item.id} className={item.id === activeConnection?.id ? 'selected' : ''} onClick={() => setSelectedConnection(item.id)}><span className={`status-dot ${connected ? 'on' : ''}`} />{item.name}{connected?.owner && <span className="agent-mark" title="Agent controlling">✦</span>}</button>; })}<button onClick={() => setShowCatalog(!showCatalog)}>＋ Connections</button><span className="fill" /></div>
        {showCatalog && <div className="catalog"><div className="row"><strong>Connection catalog</strong><span className="fill" /><button onClick={() => setEditConnection('new')}>New connection</button><button onClick={() => setShowCatalog(false)} aria-label="Close catalog">×</button></div>{snapshot.connections.map(item => <div className="settings-row" key={item.id}><strong>{item.name}</strong><span className="subtle">{item.kind === 'ssh' ? item.host : 'Local'}</span><span className="fill" /><button onClick={() => void act(() => api().setWorkspaceConnection(item.id, !snapshot.workspaceConnectionIds.includes(item.id)))}>{snapshot.workspaceConnectionIds.includes(item.id) ? 'Remove from workspace' : 'Add to workspace'}</button><button onClick={() => setEditConnection(item)}>Edit</button></div>)}</div>}
        <div className="terminal-toolbar">{activeConnection ? <><span className="subtle">{activeConnection.kind === 'ssh' ? `${activeConnection.username}@${activeConnection.host}` : 'Local shell'}</span><span className="fill" /><button className={showSplit ? 'selected' : ''} onClick={() => setShowSplit(!showSplit)} disabled={workspaceConnections.length < 2}>◫ Split</button><button className={showNotes ? 'selected' : ''} onClick={() => setShowNotes(!showNotes)}>▤ Notes</button></> : <><span className="subtle">Add a connection to this workspace to begin.</span><span className="fill" /><button className="primary" onClick={() => setEditConnection('new')}>Add connection</button></>}</div>
        <div className="stage-body">{activeConnection ? <><div className={`terminals ${showSplit && splitConnection ? 'split' : ''}`}><TerminalPane key={activeConnection.id} profile={activeConnection} session={snapshot.terminals.find(session => session.connectionId === activeConnection.id)} onConnect={() => connect(activeConnection.id)} onDisconnect={() => disconnect(activeConnection.id)} onTakeOver={() => takeOver(activeConnection.id)} />{showSplit && splitConnection && <TerminalPane key={splitConnection.id} profile={splitConnection} session={snapshot.terminals.find(session => session.connectionId === splitConnection.id)} onConnect={() => connect(splitConnection.id)} onDisconnect={() => disconnect(splitConnection.id)} onTakeOver={() => takeOver(splitConnection.id)} />}</div>{showNotes && <NotesDrawer connection={activeConnection} act={act} onClose={() => setShowNotes(false)} />}</> : <div className="terminal-empty"><span className="terminal-empty-icon">⌘</span><strong>No connections in this workspace</strong><span>Create a local shell or SSH connection to begin.</span><button className="primary" onClick={() => setEditConnection('new')}>Add connection</button></div>}</div>
      </section>
    </div>
    <footer className="statusbar"><span>◆</span> Shellmate <span className="fill" />{snapshot.workspaces.find(item => item.id === snapshot.activeWorkspaceId)?.name} · Local data</footer>
    {message && <div className="toast" role="alert"><span>{message}</span><button onClick={() => setMessage('')}>×</button></div>}
    {snapshot.hostKeys.map(request => <div className="modal-backdrop" key={request.id}><div className="dialog attention-dialog" role="dialog" aria-modal="true" aria-label="SSH host key"><h2>{request.changed ? 'SSH host key changed' : 'Trust SSH host key?'}</h2><p>{request.host}:{request.port}</p><p>SHA-256 fingerprint</p><code>{request.fingerprint}</code><p className="subtle">Verify this fingerprint using a trusted source before accepting it.</p><div className="dialog-actions"><span className="fill" /><button onClick={() => void act(() => api().trustHostKey(request.id, false))}>Reject</button><button className="primary" onClick={() => void act(() => api().trustHostKey(request.id, true))}>Trust and connect</button></div></div></div>)}
    {snapshot.elevations.map(request => <ElevationDialog key={request.id} request={request} act={act} />)}
    {editConnection && <ConnectionDialog profile={editConnection === 'new' ? undefined : editConnection} onClose={() => setEditConnection(null)} onSave={saveConnection} onDelete={editConnection === 'new' ? undefined : async () => { await api().deleteConnection(editConnection.id); await refresh(); }} />}
    {showProviders && <ProvidersDialog snapshot={snapshot} onClose={() => setShowProviders(false)} act={act} />}
  </div>;
}

function ElevationDialog({ request, act }: { request: Snapshot['elevations'][number]; act: (action: () => Promise<unknown>) => Promise<unknown> }) {
  const [password, setPassword] = useState('');
  return <div className="modal-backdrop"><div className="dialog attention-dialog" role="dialog" aria-modal="true" aria-label="Terminal password request"><h2>Terminal password requested</h2><p>The command in this terminal is waiting for a password.</p><pre>{request.command}</pre><input autoFocus type="password" aria-label="Terminal password" value={password} onChange={e => setPassword(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void act(() => api().respondElevation(request.id, password)); }} /><div className="dialog-actions"><button onClick={() => void act(() => api().respondElevation(request.id, null))}>Cancel command</button><span className="fill" /><button className="primary" onClick={() => void act(() => api().respondElevation(request.id, password))}>Send to terminal</button></div></div></div>;
}
